import { Product } from '@/lib/types'

export const mockProducts: Product[] = [
  {
    id: 'prod_1',
    sku: 'LAP-001',
    slug: 'laptop-dell-xps-13',
    name: 'Laptop Dell XPS 13',
    shortDescription: 'Laptop cao cấp mỏng nhẹ, màn hình 13 inch',
    description:
      'Laptop Dell XPS 13 với vi xử lý Intel i7, 16GB RAM, 512GB SSD. Thiết kế mỏng nhẹ, pin 14 giờ.',
    listedPrice: 24990000,
    discountAmount: 25000,
    image: '/images/laptop-dell.jpg',
    category: 'Máy tính',
    stock: 45,
    isPromotionEligible: true,
    isActive: true,
    visibility: 'visible',
    sortOrder: 1,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-07-10'),
  },
  {
    id: 'prod_2',
    sku: 'PHONE-001',
    slug: 'iphone-15-pro',
    name: 'iPhone 15 Pro',
    shortDescription: 'iPhone 15 Pro, chip A17 Pro, camera 48MP',
    description:
      'iPhone 15 Pro với chip A17 Pro, camera chính 48MP, titanium design, chế độ action.',
    listedPrice: 28990000,
    discountAmount: 25000,
    image: '/images/iphone-15.jpg',
    category: 'Điện thoại',
    stock: 32,
    isPromotionEligible: true,
    isActive: true,
    visibility: 'visible',
    sortOrder: 2,
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-07-08'),
  },
  {
    id: 'prod_3',
    sku: 'TAB-001',
    slug: 'ipad-air-11',
    name: 'iPad Air 11 inch',
    shortDescription: 'iPad Air 11 inch, chip M2, màn hình Liquid Retina',
    description:
      'iPad Air 11 inch với chip M2, màn hình Liquid Retina, hỗ trợ Apple Pencil Pro.',
    listedPrice: 15990000,
    discountAmount: 25000,
    image: '/images/ipad-air.jpg',
    category: 'Tablet',
    stock: 28,
    isPromotionEligible: true,
    isActive: true,
    visibility: 'visible',
    sortOrder: 3,
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date('2024-07-09'),
  },
  {
    id: 'prod_4',
    sku: 'WATCH-001',
    slug: 'apple-watch-series-9',
    name: 'Apple Watch Series 9',
    shortDescription: 'Apple Watch Series 9, 45mm, Always-On Retina display',
    description:
      'Apple Watch Series 9 với Always-On Retina display, S9 chip, pin 18 giờ.',
    listedPrice: 11990000,
    discountAmount: 25000,
    image: '/images/apple-watch.jpg',
    category: 'Wearable',
    stock: 56,
    isPromotionEligible: true,
    isActive: true,
    visibility: 'visible',
    sortOrder: 4,
    createdAt: new Date('2024-04-12'),
    updatedAt: new Date('2024-07-11'),
  },
  {
    id: 'prod_5',
    sku: 'HEADPHONE-001',
    slug: 'airpods-pro-2',
    name: 'AirPods Pro (2nd Generation)',
    shortDescription: 'AirPods Pro thế hệ 2, chống ồn chủ động, tai nghe true wireless',
    description:
      'AirPods Pro thế hệ 2 với chống ồn chủ động mạnh mẽ, độ trễ thấp, pin 6 giờ.',
    listedPrice: 5990000,
    discountAmount: 25000,
    image: '/images/airpods-pro.jpg',
    category: 'Âm thanh',
    stock: 78,
    isPromotionEligible: true,
    isActive: true,
    visibility: 'visible',
    sortOrder: 5,
    createdAt: new Date('2024-05-08'),
    updatedAt: new Date('2024-07-10'),
  },
  {
    id: 'prod_6',
    sku: 'CAM-001',
    slug: 'dji-air-3s',
    name: 'DJI Air 3S',
    shortDescription: 'Flycam DJI Air 3S, 48MP, quay video 4K, bay 46 phút',
    description:
      'DJI Air 3S với camera 48MP, quay video 4K/120fps, thời gian bay 46 phút, sạc nhanh.',
    listedPrice: 18990000,
    discountAmount: 25000,
    image: '/images/dji-air-3s.jpg',
    category: 'Camera',
    stock: 18,
    isPromotionEligible: true,
    isActive: true,
    visibility: 'visible',
    sortOrder: 6,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-07-07'),
  },
  {
    id: 'prod_7',
    sku: 'CHARGER-001',
    slug: 'usb-c-gan-charger-100w',
    name: 'USB-C GaN Charger 100W',
    shortDescription: 'Sạc USB-C GaN 100W, tương thích nhiều thiết bị',
    description:
      'Sạc GaN 100W với 2 cổng USB-C, tương thích MacBook, iPad, iPhone, laptop.',
    listedPrice: 1290000,
    discountAmount: 25000,
    image: '/images/charger.jpg',
    category: 'Phụ kiện',
    stock: 145,
    isPromotionEligible: false,
    isActive: true,
    visibility: 'visible',
    sortOrder: 7,
    createdAt: new Date('2024-06-01'),
    updatedAt: new Date('2024-07-11'),
  },
  {
    id: 'prod_8',
    sku: 'CABLE-001',
    slug: 'usb-c-lightning-cable',
    name: 'USB-C to Lightning Cable',
    shortDescription: 'Cáp USB-C to Lightning, 2m, hỗ trợ sạc nhanh',
    description:
      'Cáp USB-C to Lightning dài 2m, hỗ trợ sạc nhanh 30W, chống rối.',
    listedPrice: 590000,
    discountAmount: 0,
    image: '/images/cable.jpg',
    category: 'Phụ kiện',
    stock: 234,
    isPromotionEligible: false,
    isActive: true,
    visibility: 'visible',
    sortOrder: 8,
    createdAt: new Date('2024-06-15'),
    updatedAt: new Date('2024-07-11'),
  },
  {
    id: 'prod_9',
    sku: 'CASE-001',
    slug: 'airpods-case-leather',
    name: 'AirPods Case Leather',
    shortDescription: 'Bao da AirPods Pro 2, chất liệu da cao cấp',
    description: 'Bao da AirPods Pro 2 làm từ da PU cao cấp, chống xước, chống nước.',
    listedPrice: 290000,
    discountAmount: 0,
    image: '/images/airpods-case.jpg',
    category: 'Phụ kiện',
    stock: 89,
    isPromotionEligible: false,
    isActive: true,
    visibility: 'visible',
    sortOrder: 9,
    createdAt: new Date('2024-06-20'),
    updatedAt: new Date('2024-07-09'),
  },
]
