services:
  migrate:
    environment:
      DATABASE_URL: ${DATABASE_URL}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on: []

  api:
    environment:
      DATABASE_URL: ${DATABASE_URL}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on: []

  worker:
    environment:
      DATABASE_URL: ${DATABASE_URL}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on: []
